export type Role = 'admin' | 'adulto' | 'bimbo'
export type ThemeMode = 'system' | 'light' | 'dark'

export type PageKey =
  | 'home'
  | 'calendar'
  | 'shopping'
  | 'meals'
  | 'chores'
  | 'school'
  | 'board'
  | 'health'
  | 'deadlines'
  | 'todos'
  | 'users'
  | 'settings'

export type UserPrefs = {
  theme: ThemeMode
  accent: string
  density: 'compact' | 'comfortable'
  showBalances: boolean
  bottomTabs: PageKey[]
  homeCards: Array<'today' | 'shopping' | 'deadlines' | 'wallets'>
  notificationCenterReadIds?: string[]
  notifications: {
    calendar: boolean
    deadlines: boolean
    chores: boolean
    school: boolean
    board: boolean
    shopping: boolean
    whatsapp: boolean
  }
}

export type FamilyUser = {
  id: number
  cloudUserId?: string
  name: string
  role: Role
  password: string
  color: string
  avatarUrl: string
  balance: number
  prefs: UserPrefs
}

export type CalendarEvent = {
  id: number
  title: string
  date: string
  time: string
  endTime?: string
  userId: number
  userIds?: number[]
  audience?: 'users' | 'family'
  notes?: string
  linkedHealthVisitId?: number
  linkedHealthReminderType?: 'visit' | 'booking'
}

export type MedicinePackage = {
  id: number
  expiryDate?: string
  quantity: number
  packageSize?: number
  lot?: string
  addedAt?: string
}

export type TherapyMedicine = {
  id: number
  medicineId: number
  tabletsPerDose: number
  dosesPerDay: number
  usage?: string
}

export type HealthAttachment = {
  id: string
  name: string
  path: string
  mimeType?: string
  size?: number
  createdAt: string
}

export type DeadlineCategory = 'documents' | 'insurance' | 'car' | 'subscriptions' | 'school' | 'holidays' | 'birthdays' | 'home' | 'other'

export type Deadline = {
  id: number
  title: string
  date: string
  userId: number
  done: boolean
  kind?: 'general' | 'medicine' | 'therapy' | 'visit' | 'health-record'
  category?: DeadlineCategory
  reminderDays?: number[]
  repeatYearly?: boolean
  lastCompletedAt?: string
  lastCompletedDate?: string
  activeIngredient?: string
  purpose?: string
  usage?: string
  prescriber?: string
  notes?: string
  defaultPackageSize?: number
  packages?: MedicinePackage[]
  therapyStartDate?: string
  therapyEndDate?: string
  therapyMedicines?: TherapyMedicine[]
  legacyMedicineId?: number
  // Health visit / clinical history fields.
  healthStatus?: 'scheduled' | 'completed' | 'cancelled'
  time?: string
  specialty?: string
  doctor?: string
  facility?: string
  outcome?: string
  nextVisitDate?: string
  followUpEvery?: number
  followUpUnit?: 'days' | 'weeks' | 'months' | 'years'
  followUpVisitId?: number
  followUpSourceId?: number
  autoGenerated?: boolean
  calendarEventId?: number
  bookingReminderEvery?: number
  bookingReminderUnit?: 'days' | 'weeks' | 'months'
  bookingReminderEventId?: number
  healthRecordKind?: 'exam' | 'report' | 'vaccine' | 'document' | 'note'
  provider?: string
  result?: string
  attachments?: HealthAttachment[]
  // Legacy fields retained only so older backups can be migrated safely.
  stockStartDate?: string
  tabletCount?: number
  tabletsPerDose?: number
  dosesPerDay?: number
}

export type PantryLocation = 'pantry' | 'fridge' | 'freezer'

export type PantryItem = {
  id: number
  name: string
  qty: number
  unit: string
  category: string
  minQty?: number
  location?: PantryLocation
  expiryDate?: string
  autoRestock?: boolean
}

export type PantryMovement = {
  id: number
  pantryItemId: number
  delta: number
  date: string
  createdAt: string
  reason: 'manual' | 'purchase' | 'meal' | 'import' | 'adjustment'
}

export type ShoppingItem = {
  id: number
  name: string
  qty: number
  unit: string
  taken: boolean
  category?: string
}

export type Ingredient = { name: string; qty: number; unit: string }

export type Dish = {
  id: number
  name: string
  type: string
  variant: string
  ingredients: Ingredient[]
  prepMinutes?: number
  preferredByUserIds?: number[]
  sourceUrl?: string
  sourceLabel?: string
  notes?: string
}

export type MealPlan = {
  id: number
  date: string
  slot: string
  userId: number
  dishId: number
}

export type ChoreStatus = 'open' | 'pending' | 'approved'

export type Chore = {
  id: number
  title: string
  deadline: string
  userId: number
  amount: number
  done: boolean
  completionStatus?: ChoreStatus
  completedAt?: string
  completedByUserId?: number
  approvedAt?: string
  approvedByUserId?: number
  creditedTransactionId?: number
  recurringChoreId?: number
}

export type RecurringChore = {
  id: number
  title: string
  userId: number
  amount: number
  weekdays: number[]
  active: boolean
  startDate: string
  endDate?: string
}

export type Transaction = {
  id: number
  userId: number
  type: 'credit' | 'payment' | 'reversal'
  amount: number
  date: string
  note: string
  reversed?: boolean
}

export type Todo = {
  id: number
  title: string
  userId: number
  done: boolean
  createdAt: string
}

export type RoutineFrequency = 'daily' | 'weekly' | 'fortnightly' | 'monthly' | 'semiannual' | 'yearly'

export type Routine = {
  id: number
  title: string
  userId: number
  frequency: RoutineFrequency
  startDate: string
  endDate?: string
  active: boolean
  notes?: string
}

export type RoutineCompletion = {
  id: number
  routineId: number
  userId: number
  date: string
  completedAt: string
  completedByUserId: number
}

export type SchoolSubject = {
  id: number
  name: string
  shortName?: string
}

export type SchoolTimetableEntry = {
  id: number
  userId: number
  weekday: number
  order: number
  subjectId: number
  startTime?: string
  endTime?: string
  room?: string
  notes?: string
}

export type SchoolItemType = 'homework' | 'test' | 'oral' | 'material' | 'circular' | 'permission' | 'trip' | 'payment'

export type SchoolItem = {
  id: number
  userId: number
  type: SchoolItemType
  title: string
  date: string
  subjectId?: number
  notes?: string
  amount?: number
  done: boolean
  createdAt: string
}

export type BoardPostType = 'note' | 'message' | 'reminder' | 'photo'

export type BoardAttachment = {
  id: string
  name: string
  path: string
  mimeType?: string
  size?: number
  createdAt: string
}

export type BoardPost = {
  id: string
  type: BoardPostType
  title: string
  body: string
  authorUserId: number
  audience: 'family' | 'users'
  userIds: number[]
  pinned: boolean
  dueDate?: string
  createdAt: string
  updatedAt: string
  attachments: BoardAttachment[]
}

export type FamilyData = {
  version: number
  storageModel?: 'normalized-v1' | 'normalized-v2'
  assistantName: string
  users: FamilyUser[]
  calendarEvents: CalendarEvent[]
  deadlines: Deadline[]
  categories: string[]
  pantry: PantryItem[]
  pantryMovements: PantryMovement[]
  shopping: ShoppingItem[]
  dishes: Dish[]
  mealPlans: MealPlan[]
  chores: Chore[]
  recurringChores: RecurringChore[]
  transactions: Transaction[]
  todos: Todo[]
  routines: Routine[]
  routineCompletions: RoutineCompletion[]
  schoolSubjects: SchoolSubject[]
  schoolTimetable: SchoolTimetableEntry[]
  schoolItems: SchoolItem[]
  boardPosts: BoardPost[]
}
