export type Role = 'admin' | 'adulto' | 'bimbo'
export type ThemeMode = 'system' | 'light' | 'dark'
export type CurrencyCode = 'EUR' | 'USD' | 'GBP' | 'CHF'
export type VisualStyle = 'violet' | 'ocean' | 'emerald' | 'sunset' | 'berry' | 'coral' | 'midnight' | 'electric' | 'custom'
export type BackgroundPreset = 'none' | 'color' | 'aurora' | 'sky' | 'sand' | 'forest' | 'sunset' | 'night' | 'lavender' | 'custom'

export type PageKey =
  | 'home'
  | 'calendar'
  | 'shopping'
  | 'meals'
  | 'chores'
  | 'school'
  | 'board'
  | 'health'
  | 'deadlines'
  | 'todos'
  | 'reports'
  | 'users'
  | 'settings'

export type UserPrefs = {
  theme: ThemeMode
  accent: string
  visualStyle: VisualStyle
  backgroundPreset: BackgroundPreset
  backgroundColor: string
  backgroundImage?: string
  backgroundStrength: number
  backgroundBlur: number
  density: 'compact' | 'comfortable'
  showBalances: boolean
  bottomTabs: PageKey[]
  homeCards: Array<'today' | 'shopping' | 'meals' | 'school' | 'board' | 'deadlines' | 'todos' | 'wallets' | 'health'>
  notificationCenterReadIds?: string[]
  notificationDetail: 'full' | 'private'
  notifications: {
    calendar: boolean
    deadlines: boolean
    chores: boolean
    school: boolean
    board: boolean
    shopping: boolean
    whatsapp: boolean
  }
}

export type FamilyUser = {
  id: number
  cloudUserId?: string
  name: string
  role: Role
  password: string
  color: string
  avatarUrl: string
  balance: number
  prefs: UserPrefs
}

export type CalendarRecurrence = 'none' | 'daily' | 'weekly' | 'biweekly' | 'monthly' | 'yearly'

export type CalendarEvent = {
  id: number
  title: string
  date: string
  time: string
  reminderMinutes?: number[]
  endTime?: string
  userId: number
  userIds?: number[]
  audience?: 'users' | 'family'
  recurrence?: CalendarRecurrence
  recurrenceEndDate?: string
  notes?: string
  linkedHealthVisitId?: number
  linkedHealthReminderType?: 'visit' | 'booking'
}

export type MedicinePackage = {
  id: number
  expiryDate?: string
  quantity: number
  packageSize?: number
  lot?: string
  addedAt?: string
}

export type TherapyMedicine = {
  id: number
  medicineId: number
  tabletsPerDose: number
  dosesPerDay: number
  usage?: string
}

export type HealthAttachment = {
  id: string
  name: string
  path: string
  mimeType?: string
  size?: number
  createdAt: string
}

export type DeadlineCategory = 'documents' | 'insurance' | 'car' | 'subscriptions' | 'school' | 'holidays' | 'birthdays' | 'home' | 'other'

export type Deadline = {
  id: number
  title: string
  date: string
  userId: number
  done: boolean
  kind?: 'general' | 'medicine' | 'therapy' | 'visit' | 'health-record'
  category?: DeadlineCategory
  reminderDays?: number[]
  repeatYearly?: boolean
  lastCompletedAt?: string
  lastCompletedDate?: string
  activeIngredient?: string
  purpose?: string
  usage?: string
  prescriber?: string
  notes?: string
  defaultPackageSize?: number
  packages?: MedicinePackage[]
  therapyStartDate?: string
  therapyEndDate?: string
  therapyMedicines?: TherapyMedicine[]
  legacyMedicineId?: number
  // Health visit / clinical history fields.
  healthStatus?: 'scheduled' | 'completed' | 'cancelled'
  time?: string
  specialty?: string
  doctor?: string
  facility?: string
  outcome?: string
  nextVisitDate?: string
  followUpEvery?: number
  followUpUnit?: 'days' | 'weeks' | 'months' | 'years'
  followUpVisitId?: number
  followUpSourceId?: number
  autoGenerated?: boolean
  calendarEventId?: number
  bookingReminderEvery?: number
  bookingReminderUnit?: 'days' | 'weeks' | 'months'
  bookingReminderEventId?: number
  healthRecordKind?: 'exam' | 'report' | 'vaccine' | 'document' | 'note'
  provider?: string
  result?: string
  attachments?: HealthAttachment[]
  // Legacy fields retained only so older backups can be migrated safely.
  stockStartDate?: string
  tabletCount?: number
  tabletsPerDose?: number
  dosesPerDay?: number
}

export type PantryLocation = 'pantry' | 'fridge' | 'freezer'

export type PantryProductTechnicalInfo = {
  source: 'openfoodfacts'
  sourceUrl?: string
  retrievedAt: string
  confidence: number
  barcode?: string
  displayName?: string
  brand?: string
  imageUrl?: string
  packageQuantity?: string
  ingredients?: string
  allergens?: string[]
  categories?: string[]
  labels?: string[]
  nutriScore?: string
  novaGroup?: number
  ecoScore?: string
  nutriments?: {
    energyKcal100g?: number
    fat100g?: number
    saturatedFat100g?: number
    carbohydrates100g?: number
    sugars100g?: number
    fiber100g?: number
    proteins100g?: number
    salt100g?: number
  }
}

export type PantryItem = {
  id: number
  name: string
  brand?: string
  variant?: string
  packageSize?: string
  barcode?: string
  qty: number
  unit: string
  category: string
  minQty?: number
  location?: PantryLocation
  expiryDate?: string
  autoRestock?: boolean
  packageState?: 'sealed' | 'opened'
  remainingQty?: number
  remainingUnit?: string
  residualPercent?: number
  residualSource?: 'manual' | 'photo'
  productInfo?: PantryProductTechnicalInfo
}

export type PantryMovement = {
  id: number
  pantryItemId: number
  delta: number
  date: string
  createdAt: string
  reason: 'manual' | 'purchase' | 'meal' | 'import' | 'adjustment'
}

export type ShoppingItem = {
  id: number
  name: string
  qty: number
  unit: string
  taken: boolean
  category?: string
}

export type Ingredient = { name: string; qty: number; unit: string }

export type Dish = {
  id: number
  name: string
  type: string
  variant: string
  ingredients: Ingredient[]
  prepMinutes?: number
  preferredByUserIds?: number[]
  sourceUrl?: string
  sourceLabel?: string
  notes?: string
}

export type MealPlan = {
  id: number
  date: string
  slot: string
  userId: number
  dishId: number
}

export type ChoreStatus = 'open' | 'pending' | 'approved'

export type Chore = {
  id: number
  title: string
  deadline: string
  userId: number
  amount: number
  done: boolean
  completionStatus?: ChoreStatus
  completedAt?: string
  completedByUserId?: number
  approvedAt?: string
  approvedByUserId?: number
  creditedTransactionId?: number
  recurringChoreId?: number
}

export type RecurringChore = {
  id: number
  title: string
  userId: number
  userIds?: number[]
  amount: number
  weekdays: number[]
  active: boolean
  startDate: string
  endDate?: string
}

export type Transaction = {
  id: number
  userId: number
  type: 'credit' | 'payment' | 'reversal'
  amount: number
  date: string
  note: string
  reversed?: boolean
}

export type Todo = {
  id: number
  title: string
  userId: number
  done: boolean
  createdAt: string
}

export type RoutineFrequency = 'daily' | 'weekly' | 'fortnightly' | 'monthly' | 'semiannual' | 'yearly'

export type Routine = {
  id: number
  title: string
  userId: number
  frequency: RoutineFrequency
  startDate: string
  endDate?: string
  active: boolean
  notes?: string
}

export type RoutineCompletion = {
  id: number
  routineId: number
  userId: number
  date: string
  completedAt: string
  completedByUserId: number
}

export type SchoolSubject = {
  id: number
  name: string
  shortName?: string
}

export type SchoolTimetableEntry = {
  id: number
  userId: number
  weekday: number
  order: number
  subjectId: number
  startTime?: string
  endTime?: string
  room?: string
  notes?: string
}

export type SchoolItemType = 'homework' | 'test' | 'oral' | 'material' | 'circular' | 'permission' | 'trip' | 'payment'

export type SchoolItem = {
  id: number
  userId: number
  type: SchoolItemType
  title: string
  date: string
  subjectId?: number
  notes?: string
  amount?: number
  done: boolean
  createdAt: string
}

export type BoardPostType = 'note' | 'message' | 'reminder' | 'photo'

export type BoardAttachment = {
  id: string
  name: string
  path: string
  mimeType?: string
  size?: number
  createdAt: string
}

export type BoardPost = {
  id: string
  type: BoardPostType
  title: string
  body: string
  authorUserId: number
  audience: 'family' | 'users'
  userIds: number[]
  pinned: boolean
  dueDate?: string
  createdAt: string
  updatedAt: string
  attachments: BoardAttachment[]
}

export type ExpenseCategory = 'groceries' | 'dining' | 'home' | 'transport' | 'health' | 'school' | 'bills' | 'leisure' | 'clothing' | 'other'
export type ExpenseSubcategory =
  | 'dining_restaurant_bar' | 'dining_delivery'
  | 'home_mortgage_rent' | 'home_furnishings' | 'home_maintenance'
  | 'transport_fuel' | 'transport_installment' | 'transport_maintenance' | 'transport_tax_revision'
  | 'transport_insurance' | 'transport_parking_tolls' | 'transport_public' | 'transport_charging'
  | 'health_pharmacy' | 'health_visits'
  | 'school_books_stationery' | 'school_fees_activities'
  | 'bills_energy' | 'bills_phone_internet' | 'bills_banking' | 'bills_insurance'
  | 'leisure_travel' | 'leisure_subscriptions' | 'leisure_sport_entertainment'
export type ExpenseSource = 'receipt' | 'manual' | 'voice' | 'recurring' | 'bank' | 'paypal'
export type ExpenseFlow = 'expense' | 'refund'
export type ExpenseMovementKind = 'purchase' | 'fee' | 'tax' | 'bill' | 'loan' | 'cash' | 'investment' | 'card_settlement' | 'transfer' | 'paypal_repayment' | 'refund' | 'other'
export type RecurringExpenseFrequency = 'weekly' | 'monthly' | 'yearly'
export type PurchaseEvidenceSource = 'amazon_email'
export type PurchaseEvidenceStatus = 'unmatched' | 'matched' | 'review'
export type AmazonMailSyncStatus = 'idle' | 'pending' | 'running' | 'success' | 'error'

export type AmazonMailSyncState = {
  enabled: boolean
  status: AmazonMailSyncStatus
  lastRunAt?: string
  lastRequestedAt?: string
  requestedByUserId?: number
  lastImported?: number
  lastScanned?: number
  lastError?: string
}

export type ExpenseItem = {
  id: string
  name: string
  qty: number
  unit: string
  unitPrice?: number
  totalPrice?: number
  category?: string
}

export type ExpenseRecord = {
  id: string
  date: string
  merchant: string
  total: number
  category: ExpenseCategory
  subcategory?: ExpenseSubcategory
  source: ExpenseSource
  sourceRef?: string
  flow?: ExpenseFlow
  movementKind?: ExpenseMovementKind
  includeInStats?: boolean
  evidenceRefs?: string[]
  createdAt: string
  createdByUserId?: number
  notes?: string
  items: ExpenseItem[]
}

export type PurchaseEvidenceItem = {
  id: string
  name: string
  qty: number
  unitPrice?: number
  totalPrice?: number
  category?: ExpenseCategory
  subcategory?: ExpenseSubcategory
}

export type PurchaseEvidence = {
  id: string
  source: PurchaseEvidenceSource
  externalId: string
  merchant: string
  orderDate: string
  total: number
  items: PurchaseEvidenceItem[]
  status: PurchaseEvidenceStatus
  matchedExpenseId?: string
  matchConfidence?: number
  importedAt: string
  notes?: string
}

export type RecurringExpense = {
  id: string
  merchant: string
  amount: number
  category: ExpenseCategory
  subcategory?: ExpenseSubcategory
  frequency: RecurringExpenseFrequency
  startDate: string
  endDate?: string
  active: boolean
  notes?: string
  createdAt: string
  createdByUserId?: number
}

export type ApprovalRequestKind = 'calendar' | 'shopping' | 'deadline' | 'todo' | 'school'
export type ApprovalRequestAction = 'create' | 'update' | 'delete'

export type ApprovalRequest = {
  id: string
  kind: ApprovalRequestKind
  action: ApprovalRequestAction
  requestedByUserId: number
  createdAt: string
  summary: string
  payload: Record<string, any>
}

export type FamilyData = {
  version: number
  storageModel?: 'normalized-v1' | 'normalized-v2'
  assistantName: string
  currency: CurrencyCode
  users: FamilyUser[]
  calendarEvents: CalendarEvent[]
  deadlines: Deadline[]
  categories: string[]
  pantry: PantryItem[]
  pantryMovements: PantryMovement[]
  shopping: ShoppingItem[]
  dishes: Dish[]
  mealPlans: MealPlan[]
  chores: Chore[]
  recurringChores: RecurringChore[]
  transactions: Transaction[]
  todos: Todo[]
  routines: Routine[]
  routineCompletions: RoutineCompletion[]
  schoolSubjects: SchoolSubject[]
  schoolTimetable: SchoolTimetableEntry[]
  schoolItems: SchoolItem[]
  boardPosts: BoardPost[]
  approvalRequests: ApprovalRequest[]
  expenses: ExpenseRecord[]
  purchaseEvidence: PurchaseEvidence[]
  amazonMailSync: AmazonMailSyncState
  recurringExpenses: RecurringExpense[]
}
