export type Role = 'admin' | 'adulto' | 'bimbo'
export type ThemeMode = 'system' | 'light' | 'dark'

export type PageKey =
  | 'home'
  | 'calendar'
  | 'shopping'
  | 'meals'
  | 'chores'
  | 'health'
  | 'deadlines'
  | 'todos'
  | 'users'
  | 'settings'

export type UserPrefs = {
  theme: ThemeMode
  accent: string
  density: 'compact' | 'comfortable'
  showBalances: boolean
  bottomTabs: PageKey[]
  homeCards: Array<'today' | 'shopping' | 'deadlines' | 'wallets'>
  notificationCenterReadIds?: string[]
  notifications: {
    calendar: boolean
    deadlines: boolean
    chores: boolean
    shopping: boolean
    whatsapp: boolean
  }
}

export type FamilyUser = {
  id: number
  cloudUserId?: string
  name: string
  role: Role
  password: string
  color: string
  avatarUrl: string
  balance: number
  prefs: UserPrefs
}

export type CalendarEvent = {
  id: number
  title: string
  date: string
  time: string
  endTime?: string
  userId: number
  userIds?: number[]
  audience?: 'users' | 'family'
  notes?: string
  linkedHealthVisitId?: number
  linkedHealthReminderType?: 'visit' | 'booking'
}

export type MedicinePackage = {
  id: number
  expiryDate?: string
  quantity: number
  packageSize?: number
  lot?: string
  addedAt?: string
}

export type TherapyMedicine = {
  id: number
  medicineId: number
  tabletsPerDose: number
  dosesPerDay: number
  usage?: string
}

export type HealthAttachment = {
  id: string
  name: string
  path: string
  mimeType?: string
  size?: number
  createdAt: string
}

export type Deadline = {
  id: number
  title: string
  date: string
  userId: number
  done: boolean
  kind?: 'general' | 'medicine' | 'therapy' | 'visit' | 'health-record'
  activeIngredient?: string
  purpose?: string
  usage?: string
  prescriber?: string
  notes?: string
  defaultPackageSize?: number
  packages?: MedicinePackage[]
  therapyStartDate?: string
  therapyEndDate?: string
  therapyMedicines?: TherapyMedicine[]
  legacyMedicineId?: number
  // Health visit / clinical history fields.
  healthStatus?: 'scheduled' | 'completed' | 'cancelled'
  time?: string
  specialty?: string
  doctor?: string
  facility?: string
  outcome?: string
  nextVisitDate?: string
  followUpEvery?: number
  followUpUnit?: 'days' | 'weeks' | 'months' | 'years'
  followUpVisitId?: number
  followUpSourceId?: number
  autoGenerated?: boolean
  calendarEventId?: number
  bookingReminderEvery?: number
  bookingReminderUnit?: 'days' | 'weeks' | 'months'
  bookingReminderEventId?: number
  healthRecordKind?: 'exam' | 'report' | 'vaccine' | 'document' | 'note'
  provider?: string
  result?: string
  attachments?: HealthAttachment[]
  // Legacy fields retained only so older backups can be migrated safely.
  stockStartDate?: string
  tabletCount?: number
  tabletsPerDose?: number
  dosesPerDay?: number
}

export type PantryItem = {
  id: number
  name: string
  qty: number
  unit: string
  category: string
  minQty?: number
}

export type ShoppingItem = {
  id: number
  name: string
  qty: number
  unit: string
  taken: boolean
  category?: string
}

export type Ingredient = { name: string; qty: number; unit: string }

export type Dish = {
  id: number
  name: string
  type: string
  variant: string
  ingredients: Ingredient[]
}

export type MealPlan = {
  id: number
  date: string
  slot: string
  userId: number
  dishId: number
}

export type Chore = {
  id: number
  title: string
  deadline: string
  userId: number
  amount: number
  done: boolean
  creditedTransactionId?: number
  recurringChoreId?: number
}

export type RecurringChore = {
  id: number
  title: string
  userId: number
  amount: number
  weekdays: number[]
  active: boolean
  startDate: string
  endDate?: string
}

export type Transaction = {
  id: number
  userId: number
  type: 'credit' | 'payment' | 'reversal'
  amount: number
  date: string
  note: string
  reversed?: boolean
}

export type Todo = {
  id: number
  title: string
  userId: number
  done: boolean
  createdAt: string
}

export type FamilyData = {
  version: number
  users: FamilyUser[]
  calendarEvents: CalendarEvent[]
  deadlines: Deadline[]
  categories: string[]
  pantry: PantryItem[]
  shopping: ShoppingItem[]
  dishes: Dish[]
  mealPlans: MealPlan[]
  chores: Chore[]
  recurringChores: RecurringChore[]
  transactions: Transaction[]
  todos: Todo[]
}
