-- Google Calendar per-user connections and event mapping.
-- Tokens are encrypted by the Edge Function before being stored.

create table if not exists public.google_calendar_connections (
  id uuid primary key default gen_random_uuid(),
  family_id uuid not null references public.families(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  google_email text,
  refresh_token_enc text,
  personal_calendar_id text not null default 'primary',
  personal_calendar_name text,
  family_calendar_id text,
  family_calendar_name text,
  family_event_target text not null default 'personal' check (family_event_target in ('personal','shared','both')),
  enabled boolean not null default true,
  connected_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (family_id, user_id)
);

create table if not exists public.google_calendar_oauth_states (
  state text primary key,
  family_id uuid not null references public.families(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  return_to text,
  created_at timestamptz not null default now(),
  expires_at timestamptz not null default (now() + interval '10 minutes')
);

create table if not exists public.google_calendar_event_links (
  id bigint generated by default as identity primary key,
  family_id uuid not null references public.families(id) on delete cascade,
  calendar_event_id bigint not null,
  connection_id uuid not null references public.google_calendar_connections(id) on delete cascade,
  target_key text not null,
  target_kind text not null check (target_kind in ('personal','shared')),
  google_calendar_id text not null,
  google_event_id text not null,
  updated_at timestamptz not null default now(),
  unique (family_id, calendar_event_id, target_key)
);

create index if not exists google_calendar_connections_family_idx
  on public.google_calendar_connections(family_id);
create index if not exists google_calendar_event_links_family_idx
  on public.google_calendar_event_links(family_id, calendar_event_id);
create index if not exists google_calendar_oauth_states_expiry_idx
  on public.google_calendar_oauth_states(expires_at);

alter table public.google_calendar_connections enable row level security;
alter table public.google_calendar_oauth_states enable row level security;
alter table public.google_calendar_event_links enable row level security;

-- These tables are intentionally service-role only. The browser talks to the
-- google-calendar-sync Edge Function, which validates the Supabase user and
-- family membership before reading or changing anything.
revoke all on table public.google_calendar_connections from anon, authenticated;
revoke all on table public.google_calendar_oauth_states from anon, authenticated;
revoke all on table public.google_calendar_event_links from anon, authenticated;
