-- Telegram connections and automatic family report schedules.
-- Browser access is intentionally blocked; all access goes through the telegram-reports Edge Function.

create table if not exists public.telegram_connections (
  id uuid primary key default gen_random_uuid(),
  family_id uuid not null references public.families(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  chat_id bigint not null,
  telegram_user_id bigint,
  telegram_username text,
  telegram_first_name text,
  enabled boolean not null default true,
  linked_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (family_id, user_id),
  unique (chat_id)
);

create table if not exists public.telegram_link_tokens (
  token text primary key,
  family_id uuid not null references public.families(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  expires_at timestamptz not null default (now() + interval '30 minutes'),
  used_at timestamptz
);

create table if not exists public.report_schedules (
  id uuid primary key default gen_random_uuid(),
  family_id uuid not null references public.families(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null default 'Report',
  enabled boolean not null default true,
  channel text not null default 'telegram' check (channel in ('telegram')),
  time_local time not null default '07:30',
  timezone text not null default 'Europe/Rome',
  days smallint[] not null default array[1,2,3,4,5,6,7]::smallint[],
  target_day_offset smallint not null default 0 check (target_day_offset in (0,1)),
  scope text not null default 'personal' check (scope in ('personal','family')),
  sections jsonb not null default '{
    "agenda": true,
    "meals": true,
    "shopping": true,
    "lowStock": false,
    "deadlines": true,
    "todos": true,
    "chores": false
  }'::jsonb,
  include_health boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.report_delivery_logs (
  id bigint generated by default as identity primary key,
  family_id uuid not null references public.families(id) on delete cascade,
  schedule_id uuid not null references public.report_schedules(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  scheduled_key text not null,
  status text not null default 'sending' check (status in ('sending','sent','error')),
  attempts integer not null default 1,
  sent_at timestamptz,
  error text,
  message_preview text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (schedule_id, scheduled_key)
);

create table if not exists public.telegram_bot_state (
  key text primary key,
  value text not null,
  updated_at timestamptz not null default now()
);

create index if not exists telegram_connections_family_user_idx
  on public.telegram_connections(family_id, user_id);
create index if not exists telegram_link_tokens_expiry_idx
  on public.telegram_link_tokens(expires_at);
create index if not exists report_schedules_due_idx
  on public.report_schedules(enabled, family_id, user_id);
create index if not exists report_delivery_logs_schedule_idx
  on public.report_delivery_logs(schedule_id, created_at desc);

insert into public.telegram_bot_state(key, value)
values ('cron_secret', encode(extensions.gen_random_bytes(32), 'hex'))
on conflict (key) do nothing;

insert into public.telegram_bot_state(key, value)
values ('update_offset', '0')
on conflict (key) do nothing;

alter table public.telegram_connections enable row level security;
alter table public.telegram_link_tokens enable row level security;
alter table public.report_schedules enable row level security;
alter table public.report_delivery_logs enable row level security;
alter table public.telegram_bot_state enable row level security;

revoke all on table public.telegram_connections from anon, authenticated;
revoke all on table public.telegram_link_tokens from anon, authenticated;
revoke all on table public.report_schedules from anon, authenticated;
revoke all on table public.report_delivery_logs from anon, authenticated;
revoke all on table public.telegram_bot_state from anon, authenticated;

do $$
declare
  existing_job bigint;
begin
  select jobid into existing_job
  from cron.job
  where jobname = 'verdofamily_telegram_reports_minutely'
  limit 1;

  if existing_job is not null then
    perform cron.unschedule(existing_job);
  end if;
end $$;

select cron.schedule(
  'verdofamily_telegram_reports_minutely',
  '* * * * *',
  $cron$
    select net.http_post(
      url := 'https://dufenyedfayvejlxjfqj.supabase.co/functions/v1/telegram-reports',
      headers := jsonb_build_object(
        'Content-Type', 'application/json',
        'x-cron-secret', (select value from public.telegram_bot_state where key = 'cron_secret')
      ),
      body := '{"action":"cron"}'::jsonb,
      timeout_milliseconds := 50000
    );
  $cron$
);
