alter table public.family_backups
  add column if not exists health_data jsonb,
  add column if not exists backup_format_version smallint not null default 2;

create or replace function private.family_data_without_health(p_data jsonb)
returns jsonb
language sql
stable
set search_path = ''
as $$
  select jsonb_set(
    coalesce(p_data, '{}'::jsonb),
    '{deadlines}',
    coalesce((
      select jsonb_agg(e.value order by e.ord)
      from jsonb_array_elements(coalesce(p_data->'deadlines', '[]'::jsonb)) with ordinality as e(value, ord)
      where coalesce(e.value->>'kind', 'general') not in ('medicine','therapy','visit','health-record')
    ), '[]'::jsonb),
    true
  )
$$;

create or replace function private.health_backup_items(p_family_id uuid)
returns jsonb
language sql
stable
security definer
set search_path = ''
as $$
with items as (
  select
    1 as grp,
    hm.legacy_id as sort_id,
    jsonb_strip_nulls(jsonb_build_object(
      'id', hm.legacy_id,
      'title', hm.title,
      'date', hm.legacy_date,
      'userId', 0,
      'done', hm.archived,
      'kind', 'medicine',
      'activeIngredient', hm.active_ingredient,
      'purpose', hm.purpose,
      'notes', hm.notes,
      'defaultPackageSize', hm.default_package_size,
      'packages', coalesce((
        select jsonb_agg(jsonb_strip_nulls(jsonb_build_object(
          'id', hp.legacy_id,
          'expiryDate', hp.expiry_date,
          'quantity', hp.quantity,
          'packageSize', hp.package_size,
          'lot', hp.lot,
          'addedAt', hp.added_at
        )) order by hp.legacy_id)
        from public.health_medicine_packages hp
        where hp.family_id = hm.family_id and hp.medicine_id = hm.id
      ), '[]'::jsonb)
    )) as item
  from public.health_medicines hm
  where hm.family_id = p_family_id

  union all

  select
    2,
    ht.legacy_id,
    jsonb_strip_nulls(jsonb_build_object(
      'id', ht.legacy_id,
      'title', ht.title,
      'date', coalesce(ht.legacy_date, ht.end_date, ht.start_date),
      'userId', fp.legacy_user_id,
      'done', ht.archived,
      'kind', 'therapy',
      'prescriber', ht.prescriber,
      'purpose', ht.purpose,
      'notes', ht.notes,
      'therapyStartDate', ht.start_date,
      'therapyEndDate', ht.end_date,
      'therapyMedicines', coalesce((
        select jsonb_agg(jsonb_strip_nulls(jsonb_build_object(
          'id', htm.legacy_id,
          'medicineId', hm2.legacy_id,
          'tabletsPerDose', htm.tablets_per_dose,
          'dosesPerDay', htm.doses_per_day,
          'usage', htm.usage
        )) order by htm.legacy_id)
        from public.health_therapy_medicines htm
        join public.health_medicines hm2 on hm2.id = htm.medicine_id
        where htm.family_id = ht.family_id and htm.therapy_id = ht.id
      ), '[]'::jsonb),
      'attachments', coalesce((
        select jsonb_agg(jsonb_strip_nulls(jsonb_build_object(
          'id', ha.id,
          'name', ha.file_name,
          'path', ha.storage_path,
          'mimeType', ha.mime_type,
          'size', ha.file_size,
          'createdAt', ha.created_at
        )) order by ha.created_at)
        from public.health_attachments ha
        where ha.family_id = ht.family_id and ha.therapy_id = ht.id
      ), '[]'::jsonb)
    ))
  from public.health_therapies ht
  join public.family_people fp on fp.id = ht.person_id
  where ht.family_id = p_family_id

  union all

  select
    3,
    hv.legacy_id,
    jsonb_strip_nulls(jsonb_build_object(
      'id', hv.legacy_id,
      'title', hv.title,
      'date', hv.visit_date,
      'time', case when hv.visit_time is null then null else to_char(hv.visit_time, 'HH24:MI') end,
      'userId', fp.legacy_user_id,
      'done', hv.status <> 'scheduled',
      'kind', 'visit',
      'healthStatus', hv.status,
      'specialty', hv.specialty,
      'doctor', hv.doctor,
      'facility', hv.facility,
      'purpose', hv.purpose,
      'outcome', hv.outcome,
      'notes', hv.notes,
      'nextVisitDate', hv.next_visit_date,
      'followUpEvery', hv.follow_up_every,
      'followUpUnit', hv.follow_up_unit,
      'followUpVisitId', hv.follow_up_visit_legacy_id,
      'followUpSourceId', hv.follow_up_source_legacy_id,
      'autoGenerated', hv.auto_generated,
      'calendarEventId', hv.calendar_event_id,
      'bookingReminderEvery', hv.booking_reminder_every,
      'bookingReminderUnit', hv.booking_reminder_unit,
      'bookingReminderEventId', hv.booking_reminder_event_id,
      'attachments', coalesce((
        select jsonb_agg(jsonb_strip_nulls(jsonb_build_object(
          'id', ha.id,
          'name', ha.file_name,
          'path', ha.storage_path,
          'mimeType', ha.mime_type,
          'size', ha.file_size,
          'createdAt', ha.created_at
        )) order by ha.created_at)
        from public.health_attachments ha
        where ha.family_id = hv.family_id and ha.visit_id = hv.id
      ), '[]'::jsonb)
    ))
  from public.health_visits hv
  join public.family_people fp on fp.id = hv.person_id
  where hv.family_id = p_family_id

  union all

  select
    4,
    hr.legacy_id,
    jsonb_strip_nulls(jsonb_build_object(
      'id', hr.legacy_id,
      'title', hr.title,
      'date', hr.record_date,
      'userId', fp.legacy_user_id,
      'done', false,
      'kind', 'health-record',
      'healthRecordKind', hr.record_kind,
      'provider', hr.provider,
      'result', hr.result,
      'notes', hr.notes,
      'attachments', coalesce((
        select jsonb_agg(jsonb_strip_nulls(jsonb_build_object(
          'id', ha.id,
          'name', ha.file_name,
          'path', ha.storage_path,
          'mimeType', ha.mime_type,
          'size', ha.file_size,
          'createdAt', ha.created_at
        )) order by ha.created_at)
        from public.health_attachments ha
        where ha.family_id = hr.family_id and ha.record_id = hr.id
      ), '[]'::jsonb)
    ))
  from public.health_records hr
  join public.family_people fp on fp.id = hr.person_id
  where hr.family_id = p_family_id
)
select coalesce(jsonb_agg(item order by grp, sort_id), '[]'::jsonb)
from items
$$;

create or replace function private.health_backup_snapshot(p_family_id uuid)
returns jsonb
language sql
stable
security definer
set search_path = ''
as $$
  select jsonb_build_object(
    'version', 1,
    'items', private.health_backup_items(p_family_id)
  )
$$;

create or replace function private.restore_health_backup(
  p_family_id uuid,
  p_health_data jsonb,
  p_family_data jsonb
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_items jsonb;
begin
  v_items := coalesce(
    p_health_data->'items',
    (
      select coalesce(jsonb_agg(e.value order by e.ord), '[]'::jsonb)
      from jsonb_array_elements(coalesce(p_family_data->'deadlines', '[]'::jsonb)) with ordinality as e(value, ord)
      where coalesce(e.value->>'kind', 'general') in ('medicine','therapy','visit','health-record')
    ),
    '[]'::jsonb
  );

  insert into public.family_people(family_id, legacy_user_id, auth_user_id, display_name, role)
  select
    p_family_id,
    (u.value->>'id')::bigint,
    case
      when coalesce(u.value->>'cloudUserId','') ~* '^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$'
        then (u.value->>'cloudUserId')::uuid
      else null
    end,
    coalesce(nullif(u.value->>'name',''), 'Familiare'),
    case coalesce(u.value->>'role','adulto')
      when 'admin' then 'admin'
      when 'bimbo' then 'child'
      else 'adult'
    end
  from jsonb_array_elements(coalesce(p_family_data->'users','[]'::jsonb)) u(value)
  where coalesce(u.value->>'id','') ~ '^[0-9]+$'
  on conflict (family_id, legacy_user_id) do update
  set auth_user_id = excluded.auth_user_id,
      display_name = excluded.display_name,
      role = excluded.role,
      updated_at = now();

  delete from public.health_attachments where family_id = p_family_id;
  delete from public.health_therapy_medicines where family_id = p_family_id;
  delete from public.health_visits where family_id = p_family_id;
  delete from public.health_records where family_id = p_family_id;
  delete from public.health_therapies where family_id = p_family_id;
  delete from public.health_medicine_packages where family_id = p_family_id;
  delete from public.health_medicines where family_id = p_family_id;

  insert into public.health_medicines(
    family_id, legacy_id, title, legacy_date, active_ingredient, purpose, notes, default_package_size, archived
  )
  select
    p_family_id,
    (d.value->>'id')::bigint,
    coalesce(nullif(d.value->>'title',''), 'Medicinale'),
    nullif(d.value->>'date','')::date,
    nullif(d.value->>'activeIngredient',''),
    nullif(d.value->>'purpose',''),
    nullif(d.value->>'notes',''),
    nullif(d.value->>'defaultPackageSize','')::numeric,
    coalesce((d.value->>'done')::boolean, false)
  from jsonb_array_elements(v_items) d(value)
  where d.value->>'kind' = 'medicine'
    and coalesce(d.value->>'id','') ~ '^[0-9]+$';

  insert into public.health_medicine_packages(
    family_id, medicine_id, legacy_id, expiry_date, quantity, package_size, lot, added_at
  )
  select
    p_family_id,
    hm.id,
    coalesce(nullif(pkg.value->>'id','')::bigint, pkg.ordinality::bigint),
    nullif(pkg.value->>'expiryDate','')::date,
    greatest(coalesce(nullif(pkg.value->>'quantity','')::numeric,0),0),
    nullif(pkg.value->>'packageSize','')::numeric,
    nullif(pkg.value->>'lot',''),
    nullif(pkg.value->>'addedAt','')::date
  from jsonb_array_elements(v_items) d(value)
  join public.health_medicines hm
    on hm.family_id = p_family_id and hm.legacy_id = (d.value->>'id')::bigint
  cross join lateral jsonb_array_elements(coalesce(d.value->'packages','[]'::jsonb)) with ordinality pkg(value, ordinality)
  where d.value->>'kind' = 'medicine'
    and coalesce(d.value->>'id','') ~ '^[0-9]+$';

  insert into public.health_therapies(
    family_id, legacy_id, person_id, title, legacy_date, start_date, end_date, prescriber, purpose, notes, archived
  )
  select
    p_family_id,
    (d.value->>'id')::bigint,
    fp.id,
    coalesce(nullif(d.value->>'title',''), 'Terapia'),
    nullif(d.value->>'date','')::date,
    coalesce(nullif(d.value->>'therapyStartDate','')::date, nullif(d.value->>'date','')::date, current_date),
    nullif(d.value->>'therapyEndDate','')::date,
    nullif(d.value->>'prescriber',''),
    nullif(d.value->>'purpose',''),
    nullif(d.value->>'notes',''),
    coalesce((d.value->>'done')::boolean, false)
  from jsonb_array_elements(v_items) d(value)
  join public.family_people fp
    on fp.family_id = p_family_id and fp.legacy_user_id = (d.value->>'userId')::bigint
  where d.value->>'kind' = 'therapy'
    and coalesce(d.value->>'id','') ~ '^[0-9]+$'
    and coalesce(d.value->>'userId','') ~ '^[0-9]+$';

  insert into public.health_therapy_medicines(
    family_id, therapy_id, medicine_id, legacy_id, tablets_per_dose, doses_per_day, usage
  )
  select
    p_family_id,
    ht.id,
    hm.id,
    coalesce(nullif(line.value->>'id','')::bigint, line.ordinality::bigint),
    greatest(coalesce(nullif(line.value->>'tabletsPerDose','')::numeric,1),0.001),
    greatest(coalesce(nullif(line.value->>'dosesPerDay','')::numeric,1),0.001),
    nullif(line.value->>'usage','')
  from jsonb_array_elements(v_items) d(value)
  join public.health_therapies ht
    on ht.family_id = p_family_id and ht.legacy_id = (d.value->>'id')::bigint
  cross join lateral jsonb_array_elements(coalesce(d.value->'therapyMedicines','[]'::jsonb)) with ordinality line(value, ordinality)
  join public.health_medicines hm
    on hm.family_id = p_family_id and hm.legacy_id = (line.value->>'medicineId')::bigint
  where d.value->>'kind' = 'therapy'
    and coalesce(line.value->>'medicineId','') ~ '^[0-9]+$';

  insert into public.health_visits(
    family_id, legacy_id, person_id, title, visit_date, visit_time, status,
    specialty, doctor, facility, purpose, outcome, notes, next_visit_date,
    follow_up_every, follow_up_unit, follow_up_visit_legacy_id, follow_up_source_legacy_id,
    auto_generated, calendar_event_id, booking_reminder_every, booking_reminder_unit,
    booking_reminder_event_id
  )
  select
    p_family_id,
    (d.value->>'id')::bigint,
    fp.id,
    coalesce(nullif(d.value->>'title',''), 'Visita'),
    coalesce(nullif(d.value->>'date','')::date, current_date),
    nullif(d.value->>'time','')::time,
    case
      when d.value->>'healthStatus' in ('scheduled','completed','cancelled') then d.value->>'healthStatus'
      when coalesce((d.value->>'done')::boolean,false) then 'completed'
      else 'scheduled'
    end,
    nullif(d.value->>'specialty',''),
    nullif(d.value->>'doctor',''),
    nullif(d.value->>'facility',''),
    nullif(d.value->>'purpose',''),
    nullif(d.value->>'outcome',''),
    nullif(d.value->>'notes',''),
    nullif(d.value->>'nextVisitDate','')::date,
    nullif(d.value->>'followUpEvery','')::integer,
    nullif(d.value->>'followUpUnit',''),
    nullif(d.value->>'followUpVisitId','')::bigint,
    nullif(d.value->>'followUpSourceId','')::bigint,
    coalesce((d.value->>'autoGenerated')::boolean,false),
    nullif(d.value->>'calendarEventId','')::bigint,
    nullif(d.value->>'bookingReminderEvery','')::integer,
    nullif(d.value->>'bookingReminderUnit',''),
    nullif(d.value->>'bookingReminderEventId','')::bigint
  from jsonb_array_elements(v_items) d(value)
  join public.family_people fp
    on fp.family_id = p_family_id and fp.legacy_user_id = (d.value->>'userId')::bigint
  where d.value->>'kind' = 'visit'
    and coalesce(d.value->>'id','') ~ '^[0-9]+$'
    and coalesce(d.value->>'userId','') ~ '^[0-9]+$';

  insert into public.health_records(
    family_id, legacy_id, person_id, title, record_date, record_kind, provider, result, notes
  )
  select
    p_family_id,
    (d.value->>'id')::bigint,
    fp.id,
    coalesce(nullif(d.value->>'title',''), 'Documento sanitario'),
    coalesce(nullif(d.value->>'date','')::date, current_date),
    case when d.value->>'healthRecordKind' in ('exam','report','vaccine','document','note')
      then d.value->>'healthRecordKind' else 'document' end,
    nullif(d.value->>'provider',''),
    nullif(d.value->>'result',''),
    nullif(d.value->>'notes','')
  from jsonb_array_elements(v_items) d(value)
  join public.family_people fp
    on fp.family_id = p_family_id and fp.legacy_user_id = (d.value->>'userId')::bigint
  where d.value->>'kind' = 'health-record'
    and coalesce(d.value->>'id','') ~ '^[0-9]+$'
    and coalesce(d.value->>'userId','') ~ '^[0-9]+$';

  insert into public.health_attachments(
    id, family_id, visit_id, storage_path, file_name, mime_type, file_size, created_at
  )
  select
    case when coalesce(a.value->>'id','') ~* '^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$'
      then (a.value->>'id')::uuid else gen_random_uuid() end,
    p_family_id,
    hv.id,
    a.value->>'path',
    coalesce(nullif(a.value->>'name',''), 'allegato'),
    nullif(a.value->>'mimeType',''),
    nullif(a.value->>'size','')::bigint,
    coalesce(nullif(a.value->>'createdAt','')::timestamptz, now())
  from jsonb_array_elements(v_items) d(value)
  join public.health_visits hv
    on hv.family_id = p_family_id and hv.legacy_id = (d.value->>'id')::bigint
  cross join lateral jsonb_array_elements(coalesce(d.value->'attachments','[]'::jsonb)) a(value)
  where d.value->>'kind' = 'visit'
    and coalesce(a.value->>'path','') <> '';

  insert into public.health_attachments(
    id, family_id, therapy_id, storage_path, file_name, mime_type, file_size, created_at
  )
  select
    case when coalesce(a.value->>'id','') ~* '^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$'
      then (a.value->>'id')::uuid else gen_random_uuid() end,
    p_family_id,
    ht.id,
    a.value->>'path',
    coalesce(nullif(a.value->>'name',''), 'allegato'),
    nullif(a.value->>'mimeType',''),
    nullif(a.value->>'size','')::bigint,
    coalesce(nullif(a.value->>'createdAt','')::timestamptz, now())
  from jsonb_array_elements(v_items) d(value)
  join public.health_therapies ht
    on ht.family_id = p_family_id and ht.legacy_id = (d.value->>'id')::bigint
  cross join lateral jsonb_array_elements(coalesce(d.value->'attachments','[]'::jsonb)) a(value)
  where d.value->>'kind' = 'therapy'
    and coalesce(a.value->>'path','') <> '';

  insert into public.health_attachments(
    id, family_id, record_id, storage_path, file_name, mime_type, file_size, created_at
  )
  select
    case when coalesce(a.value->>'id','') ~* '^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$'
      then (a.value->>'id')::uuid else gen_random_uuid() end,
    p_family_id,
    hr.id,
    a.value->>'path',
    coalesce(nullif(a.value->>'name',''), 'allegato'),
    nullif(a.value->>'mimeType',''),
    nullif(a.value->>'size','')::bigint,
    coalesce(nullif(a.value->>'createdAt','')::timestamptz, now())
  from jsonb_array_elements(v_items) d(value)
  join public.health_records hr
    on hr.family_id = p_family_id and hr.legacy_id = (d.value->>'id')::bigint
  cross join lateral jsonb_array_elements(coalesce(d.value->'attachments','[]'::jsonb)) a(value)
  where d.value->>'kind' = 'health-record'
    and coalesce(a.value->>'path','') <> '';
end;
$$;

update public.family_backups b
set
  health_data = jsonb_build_object(
    'version', 1,
    'items', coalesce((
      select jsonb_agg(e.value order by e.ord)
      from jsonb_array_elements(coalesce(b.data->'deadlines', '[]'::jsonb)) with ordinality as e(value, ord)
      where coalesce(e.value->>'kind', 'general') in ('medicine','therapy','visit','health-record')
    ), '[]'::jsonb)
  ),
  data = private.family_data_without_health(b.data),
  backup_format_version = 2
where b.health_data is null;

alter table public.family_backups
  alter column health_data set default '{"version":1,"items":[]}'::jsonb,
  alter column health_data set not null;

create or replace function public.backup_family_document_before_update()
returns trigger
language plpgsql
security definer
set search_path = public, private, pg_temp
as $$
begin
  if current_setting('app.skip_family_backup_trigger', true) = 'on' then
    return new;
  end if;

  insert into public.family_backups(
    family_id, revision, data, health_data, backup_format_version, reason, created_by
  )
  values (
    old.family_id,
    old.revision,
    private.family_data_without_health(old.data),
    private.health_backup_snapshot(old.family_id),
    2,
    'auto_before_update',
    old.updated_by
  );

  delete from public.family_backups b
  where b.family_id = old.family_id
    and b.id in (
      select id
      from public.family_backups
      where family_id = old.family_id
      order by created_at desc
      offset 500
    );

  return new;
end;
$$;

create or replace function public.create_family_backup(p_family_id uuid, p_reason text default 'manual')
returns bigint
language plpgsql
security definer
set search_path = public, private, pg_temp
as $$
declare
  v_id bigint;
  v_role text;
begin
  if auth.uid() is null then raise exception 'not_authenticated'; end if;

  v_role := private.family_role(p_family_id, auth.uid());
  if v_role not in ('admin','adult') then
    raise exception 'adult_or_admin_required';
  end if;

  insert into public.family_backups(
    family_id, revision, data, health_data, backup_format_version, reason, created_by
  )
  select
    family_id,
    revision,
    private.family_data_without_health(data),
    private.health_backup_snapshot(family_id),
    2,
    coalesce(nullif(trim(p_reason), ''), 'manual'),
    auth.uid()
  from public.family_documents
  where family_id = p_family_id
  returning id into v_id;

  if v_id is null then raise exception 'family_document_not_found'; end if;
  return v_id;
end;
$$;

create or replace function public.restore_family_backup(p_backup_id bigint)
returns bigint
language plpgsql
security definer
set search_path = public, private, pg_temp
as $$
declare
  v_family_id uuid;
  v_data jsonb;
  v_health_data jsonb;
  v_revision bigint;
begin
  if auth.uid() is null then raise exception 'not_authenticated'; end if;

  select b.family_id, b.data, b.health_data
  into v_family_id, v_data, v_health_data
  from public.family_backups b
  where b.id = p_backup_id;

  if v_family_id is null then raise exception 'backup_not_found'; end if;
  if not private.is_family_admin(v_family_id, auth.uid()) then
    raise exception 'family_admin_required';
  end if;

  insert into public.family_backups(
    family_id, revision, data, health_data, backup_format_version, reason, created_by
  )
  select
    fd.family_id,
    fd.revision,
    private.family_data_without_health(fd.data),
    private.health_backup_snapshot(fd.family_id),
    2,
    'pre_restore',
    auth.uid()
  from public.family_documents fd
  where fd.family_id = v_family_id;

  perform private.restore_health_backup(v_family_id, v_health_data, v_data);

  perform set_config('app.skip_family_backup_trigger', 'on', true);
  update public.family_documents
  set data = private.family_data_without_health(v_data),
      revision = revision + 1,
      updated_by = auth.uid(),
      updated_at = now()
  where family_id = v_family_id
  returning revision into v_revision;
  perform set_config('app.skip_family_backup_trigger', 'off', true);

  if v_revision is null then raise exception 'family_document_not_found'; end if;
  return v_revision;
end;
$$;

create or replace function public.system_health_snapshot(p_family_id uuid)
returns jsonb
language sql
stable
security definer
set search_path = ''
as $$
  select private.health_backup_snapshot(p_family_id)
$$;

revoke all on function private.family_data_without_health(jsonb) from public, anon, authenticated;
revoke all on function private.health_backup_items(uuid) from public, anon, authenticated;
revoke all on function private.health_backup_snapshot(uuid) from public, anon, authenticated;
revoke all on function private.restore_health_backup(uuid, jsonb, jsonb) from public, anon, authenticated;

revoke execute on function public.create_family_backup(uuid,text) from public, anon;
grant execute on function public.create_family_backup(uuid,text) to authenticated;

revoke execute on function public.restore_family_backup(bigint) from public, anon;
grant execute on function public.restore_family_backup(bigint) to authenticated;

revoke execute on function public.system_health_snapshot(uuid) from public, anon, authenticated;
grant execute on function public.system_health_snapshot(uuid) to service_role;
