-- VerdoFamily current backend recovery snapshot
-- Captured from the live Supabase project on 2026-09-15.
-- Apply AFTER the initial family backend migration.
-- No credentials, webhook secrets or user data are stored in this file.

create extension if not exists pgcrypto;
create extension if not exists pg_net;
create extension if not exists pg_cron;

-- -----------------------------------------------------------------------------
-- Backup history
-- -----------------------------------------------------------------------------

create table if not exists public.family_backups (
  id bigint generated by default as identity primary key,
  family_id uuid not null references public.families(id) on delete cascade,
  revision bigint not null,
  data jsonb not null,
  reason text not null default 'auto',
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

create index if not exists family_backups_family_created_idx
  on public.family_backups (family_id, created_at desc);

alter table public.family_backups enable row level security;

drop policy if exists "family members can read backups" on public.family_backups;
create policy "family members can read backups"
on public.family_backups for select
to authenticated
using (
  exists (
    select 1 from public.family_members fm
    where fm.family_id = family_backups.family_id
      and fm.user_id = auth.uid()
  )
);

-- -----------------------------------------------------------------------------
-- Google Drive backup configuration
-- -----------------------------------------------------------------------------

create table if not exists public.drive_backup_configs (
  family_id uuid primary key references public.families(id) on delete cascade,
  webhook_url text not null,
  webhook_secret text not null,
  enabled boolean not null default true,
  last_attempt_at timestamptz,
  last_success_at timestamptz,
  last_error text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.drive_backup_configs enable row level security;

drop policy if exists "family owners can insert drive backup config" on public.drive_backup_configs;
create policy "family owners can insert drive backup config"
on public.drive_backup_configs for insert
to authenticated
with check (
  exists (
    select 1 from public.families f
    where f.id = drive_backup_configs.family_id
      and f.owner_id = auth.uid()
  )
);

drop policy if exists "family owners can read drive backup config" on public.drive_backup_configs;
create policy "family owners can read drive backup config"
on public.drive_backup_configs for select
to authenticated
using (
  exists (
    select 1 from public.families f
    where f.id = drive_backup_configs.family_id
      and f.owner_id = auth.uid()
  )
);

drop policy if exists "family owners can update drive backup config" on public.drive_backup_configs;
create policy "family owners can update drive backup config"
on public.drive_backup_configs for update
to authenticated
using (
  exists (
    select 1 from public.families f
    where f.id = drive_backup_configs.family_id
      and f.owner_id = auth.uid()
  )
)
with check (
  exists (
    select 1 from public.families f
    where f.id = drive_backup_configs.family_id
      and f.owner_id = auth.uid()
  )
);

-- Internal-only key/value store. RLS intentionally has no client policies.
create table if not exists public.system_settings (
  key text primary key,
  value text not null,
  updated_at timestamptz not null default now()
);

alter table public.system_settings enable row level security;

-- -----------------------------------------------------------------------------
-- Functions added after the initial backend
-- -----------------------------------------------------------------------------

create or replace function public.bootstrap_family_document(p_family_id uuid, p_data jsonb)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  v_uid uuid := auth.uid();
  v_revision bigint;
begin
  if v_uid is null then raise exception 'not_authenticated'; end if;
  if not public.is_family_admin(p_family_id, v_uid) then raise exception 'not_family_admin'; end if;

  update public.family_documents
  set data = coalesce(p_data, '{}'::jsonb),
      revision = revision + 1,
      updated_by = v_uid,
      updated_at = now()
  where family_id = p_family_id
    and (data = '{}'::jsonb or data is null)
  returning revision into v_revision;

  if v_revision is null then raise exception 'family_document_already_initialized'; end if;
  return v_revision;
end;
$$;

create or replace function public.backup_family_document_before_update()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.family_backups(family_id, revision, data, reason, created_by)
  values (old.family_id, old.revision, old.data, 'auto_before_update', old.updated_by);

  delete from public.family_backups b
  where b.family_id = old.family_id
    and b.id in (
      select id
      from public.family_backups
      where family_id = old.family_id
      order by created_at desc
      offset 500
    );

  return new;
end;
$$;

drop trigger if exists trg_backup_family_document_before_update on public.family_documents;
create trigger trg_backup_family_document_before_update
before update on public.family_documents
for each row execute function public.backup_family_document_before_update();

create or replace function public.create_family_backup(
  p_family_id uuid,
  p_reason text default 'manual'
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  v_id bigint;
begin
  if not exists (
    select 1 from public.family_members
    where family_id = p_family_id and user_id = auth.uid()
  ) then
    raise exception 'not_authorized';
  end if;

  insert into public.family_backups(family_id, revision, data, reason, created_by)
  select family_id,
         revision,
         data,
         coalesce(nullif(trim(p_reason), ''), 'manual'),
         auth.uid()
  from public.family_documents
  where family_id = p_family_id
  returning id into v_id;

  return v_id;
end;
$$;

create or replace function public.restore_family_backup(p_backup_id bigint)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  v_family_id uuid;
  v_data jsonb;
  v_role text;
  v_revision bigint;
begin
  select b.family_id, b.data
  into v_family_id, v_data
  from public.family_backups b
  where b.id = p_backup_id;

  if v_family_id is null then
    raise exception 'backup_not_found';
  end if;

  select fm.role
  into v_role
  from public.family_members fm
  where fm.family_id = v_family_id
    and fm.user_id = auth.uid();

  if v_role not in ('admin', 'adult') then
    raise exception 'not_authorized';
  end if;

  insert into public.family_backups (family_id, revision, data, reason, created_by)
  select fd.family_id, fd.revision, fd.data, 'pre_restore', auth.uid()
  from public.family_documents fd
  where fd.family_id = v_family_id;

  update public.family_documents
  set data = v_data,
      revision = revision + 1,
      updated_by = auth.uid(),
      updated_at = now()
  where family_id = v_family_id
  returning revision into v_revision;

  return v_revision;
end;
$$;

create or replace function public.configure_drive_backup(
  p_family_id uuid,
  p_webhook_url text,
  p_webhook_secret text,
  p_enabled boolean default true
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if not exists (
    select 1 from public.families
    where id = p_family_id and owner_id = auth.uid()
  ) then
    raise exception 'not_authorized';
  end if;

  if p_webhook_url !~ '^https://script\.google\.com/'
     and p_webhook_url !~ '^https://script\.googleusercontent\.com/' then
    raise exception 'invalid_google_apps_script_url';
  end if;

  insert into public.drive_backup_configs(
    family_id, webhook_url, webhook_secret, enabled, updated_at
  )
  values (
    p_family_id, trim(p_webhook_url), p_webhook_secret, p_enabled, now()
  )
  on conflict (family_id) do update
    set webhook_url = excluded.webhook_url,
        webhook_secret = excluded.webhook_secret,
        enabled = excluded.enabled,
        updated_at = now();
end;
$$;

create or replace function public.disable_drive_backup(p_family_id uuid)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if not exists (
    select 1 from public.families
    where id = p_family_id and owner_id = auth.uid()
  ) then
    raise exception 'not_authorized';
  end if;

  update public.drive_backup_configs
  set enabled = false, updated_at = now()
  where family_id = p_family_id;
end;
$$;

create or replace function public.get_drive_backup_status(p_family_id uuid)
returns table(
  enabled boolean,
  last_attempt_at timestamptz,
  last_success_at timestamptz,
  last_error text
)
language sql
set search_path = public
as $$
  select c.enabled, c.last_attempt_at, c.last_success_at, c.last_error
  from public.drive_backup_configs c
  where c.family_id = p_family_id;
$$;

-- -----------------------------------------------------------------------------
-- Function permissions
-- -----------------------------------------------------------------------------

revoke execute on function public.backup_family_document_before_update() from public, anon, authenticated;

revoke execute on function public.bootstrap_family_document(uuid, jsonb) from public, anon;
revoke execute on function public.configure_drive_backup(uuid, text, text, boolean) from public, anon;
revoke execute on function public.create_family_backup(uuid, text) from public, anon;
revoke execute on function public.disable_drive_backup(uuid) from public, anon;
revoke execute on function public.get_drive_backup_status(uuid) from public, anon;
revoke execute on function public.restore_family_backup(bigint) from public, anon;

grant execute on function public.bootstrap_family_document(uuid, jsonb) to authenticated;
grant execute on function public.configure_drive_backup(uuid, text, text, boolean) to authenticated;
grant execute on function public.create_family_backup(uuid, text) to authenticated;
grant execute on function public.disable_drive_backup(uuid) to authenticated;
grant execute on function public.get_drive_backup_status(uuid) to authenticated;
grant execute on function public.restore_family_backup(bigint) to authenticated;

-- Secrets and the pg_cron job are intentionally not embedded here.
-- See supabase/ops/configure_daily_drive_cron.sql and docs/RECOVERY.md.
